#!/bin/bash

PROJECT_DIR="$(cd "$($HOME/repos/aoc-machine/ "$0")" && pwd)"
cd "$PROJECT_DIR" || exit 1
echo $PROJECT_DIR
export PYTHONPATH="$PROJECT_DIR"
echo $PYTHONPATH
poetry run python main.py "$@"
