#!/bin/bash

PROJECT_DIR=$HOME/repos/aoc-machine
cd "$PROJECT_DIR" || exit 1
echo "Project directory: $PROJECT_DIR"

export PYTHONPATH="$PROJECT_DIR"
echo "PYTHONPATH: $PYTHONPATH"

python3 main.py "$@"
